apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-sa
  labels:
    app: hw
spec:
  replicas: 3
  selector:
    matchLabels:
      name: hw
  template:
    metadata:
      labels:
        name: hw
    spec:
      containers:
        - name: api
          image: 21magzhan/hw-sa
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 90
            periodSeconds: 10
---            
apiVersion: v1
kind: Service
metadata:
  name: hw
spec:
  ports:
    - port: 8000
  selector:
    name: hws
  type: NodePort